// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeQO4ZmPKgpXIcDc3DFRxqsidAqeLYHy4',
    appId: '1:1009895765031:web:c6719f1205a42511570a02',
    messagingSenderId: '1009895765031',
    projectId: 'familyguard-app-e2b30',
    authDomain: 'familyguard-app-e2b30.firebaseapp.com',
    storageBucket: 'familyguard-app-e2b30.firebasestorage.app',
    measurementId: 'G-WB0JEXNJ6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMO0lzXdG41i0QIG8H8LkcyQZv9N5dqZo',
    appId: '1:1009895765031:android:2fc2c391f54d1353570a02',
    messagingSenderId: '1009895765031',
    projectId: 'familyguard-app-e2b30',
    storageBucket: 'familyguard-app-e2b30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJzunpqcT3CCnyNYXhGY6ZHrCLxge3MkQ',
    appId: '1:1009895765031:ios:09042e5dd9bd7a0e570a02',
    messagingSenderId: '1009895765031',
    projectId: 'familyguard-app-e2b30',
    storageBucket: 'familyguard-app-e2b30.firebasestorage.app',
    iosBundleId: 'com.familyguard.app',
  );
}
